services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-llama3.1-8b
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11438:11434"
    environment:
      - OLLAMA_NUM_PARALLEL=8
      - OLLAMA_CONTEXT_LENGTH=4096
    runtime: nvidia
    entrypoint: ["/bin/sh"]
    command:
      - -c
      - |
        echo 'Starting Ollama...';
        ollama serve &
        sleep 15

        echo 'Pulling llama3.1-8b...';
        ollama pull llama3.1:latest

        echo 'Ready.';
        wait
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 40s
      timeout: 20s
      retries: 3
      start_period: 30s
    restart: on-failure
volumes:
  ollama_data: